main/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.index, name='index'),
   path('create/', views.create_post, name='create_post'),
   path('blog/', views.blog, name='blog'),
   path('about/', views.about, name='about'),
   path('contact/', views.contact, name='contact'),
   path('nav/', views.nav, name='nav'),
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('compras/', views.compras, name='compras'),
     path('comprar/<int:producto_id>/', views.comprar_producto, name='comprar_producto'),
]

trazart/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.IntegerField(10)
    comments = models.TextField()

class Post(models.Model):
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='static/images/fotoblog', blank=True)
    content = models.TextField()
    author = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)


shop/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    item = models.CharField(max_length=100)
    detalle = models.TextField()
    foto = models.ImageField(upload_to='static/images')
    precio = models.DecimalField(max_digits=8, decimal_places=2)


main/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'photo']
        labels = {
            'title': 'Título',
            'content': 'Contenido',
            'author': 'Autor',
            'photo': 'Foto'
        }

main/views.py
from django.shortcuts import render, redirect
from .models import Contact, Post
from .forms import PostForm


# Create your views here.

def index(request):
    return render(request, 'index.html')

def nav(request):
    return render(request, 'nav.html')

# Sección Blog
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog')
    else:
        form = PostForm()
    
    context = {'form': form}
    return render(request, 'create_post.html', context)

def blog(request):
    posts = Post.objects.all()
    return render(request, 'blog.html', {'posts': posts})

# Fin Sección Blog

def about(request):
    return render(request, 'about.html')

# Sección Contacto
def contact(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        comments = request.POST.get('comments')

        contact = Contact(first_name=first_name, last_name=last_name, email=email, phone=phone, comments=comments)
        contact.save()

        return render(request, 'contactok.html')

    return render(request, 'contact.html')
# Fin Sección Contacto

shop/views.py
from django.shortcuts import render, redirect
from .models import Producto


# Create your views here.

def compras(request):
    productos = Producto.objects.all()
    return render(request, 'compras.html', {'productos': productos})

def comprar_producto(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    return redirect('compras')

main/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>About</title>
</head>
<body>
    {% extends 'nav.html' %}

    {% block content %}
    <h1>Sobre Nosotros...</h1>
    {% endblock %}
    
</body>
</html>

main/templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>Blog</title>

<style>
   /* Estilos para la galería */
.gallery {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

/* Estilos para cada publicación */
.post {
    width: 30%;
    margin-bottom: 20px;
    padding: 10px;
    background-color: #f9f9f9;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.post h2 {
    font-size: 20px;
    margin-bottom: 10px;
    color: #333;
}

.post img {
    width: 100%;
    height: 400px; /* Tamaño uniforme para cada imagen */
    object-fit: cover; /* Ajusta la imagen dentro del contenedor */
    margin-bottom: 10px;
}

.post p {
    font-size: 14px;
    margin-bottom: 5px;
    color: #666;
}

.post p.author {
    font-size: 12px;
    color: #888;
}

.post hr {
    margin: 10px 0;
}
</style>


</head>
<body>
    {% extends 'nav.html' %}

    {% block content %}
    <h1>Tus ideas hechas realidad...</h1>

    <div class="gallery">
        {% for post in posts %}
            <div class="post">
                <h2>{{ post.title }}</h2>
                <img src="{{ post.photo.url }}" alt="Foto">
                <p>{{ post.content }}</p>
                <p>Autor/es: {{ post.author }}</p>
                <hr>
            </div>
        {% empty %}
            <p>No posts yet.</p>
        {% endfor %}
    </div>
    {% endblock %}

</body>
</html>

main/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>Contacto</title>
</head>
<body>
    {% extends 'nav.html' %}

    {% block content %}
    <h1>Formulario de Contacto</h1>
    <br>
    <form method="POST" action="{% url 'contact' %}">
        {% csrf_token %}
        <label for="id_first_name">Nombre:</label>
        <input type="text" id="id_first_name" name="first_name" required><br><br>

        <label for="id_last_name">Apellido:</label>
        <input type="text" id="id_last_name" name="last_name" required><br><br>

        <label for="id_email">Email:</label>
        <input type="email" id="id_email" name="email" required><br><br>

        <label for="id_phone">Teléfono:</label>
        <input type="tel" id="id_phone" name="phone" required><br><br>

        <label for="id_comments">Comentarios:</label>
        <textarea id="id_comments" name="comments" required></textarea><br><br>

        <input type="submit" value="Enviar">
    
    {% endblock %}
    
</body>
</html>

main/templates/contactok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>Datos procesados...</title>
</head>
<body>
    {% extends 'nav.html' %}

    {% block content %}
    <h1>Información recibida correctamente</h1>
    <h2>Nos contactaremos a la brevedad...</h2>
    {% endblock %}
    
</body>
</html>

main/templates/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>Crear Post</title>
</head>
<body>
    {% extends 'nav.html' %}
    {% block content %}
    <h1>Crear un nuevo post para el Blog</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Crear</button>
    </form>
    {% endblock %}
</body>
</html>

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="static/css/styles.css">
    <title>Trazart - Diseños en madera MDF</title>
        
</head>
<body>
    
    {% extends 'nav.html' %}

    {% block content %}
        <h1>Bienvenid@s!!!</h1>
        <div class="container">    
            <div class="logo">
                <img src="static/images/logo.jpg" alt="Logo">
            </div>
        </div>
    {% endblock %}
    
</body>
</html>

main/templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>NavBar</title>
    
    <style>
        nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #f1f1f1;
    }

    nav li {
        float: left;
    }

    nav li a {
        display: block;
        color: #333;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    nav li a:hover {
        background-color: #ddd;
    }
    </style>
    
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">Inicio</a></li>
            <li><a href="{% url 'create_post' %}">Crear Post</a></li>
            <li><a href="{% url 'blog' %}">Blog</a></li>
            <li><a href="{% url 'contact' %}">Contacto</a></li>
            <li><a href="{% url 'about' %}">Nosotros</a></li>
            <li><a href="{% url 'compras' %}">Compras</a></li>
        </ul>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

shop/templates/compras.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="main/css/styles.css">
    <title>Carrito de Compra</title>
</head>
<body>
    {% extends 'nav.html' %}

    {% block content %}
    <h1>Carrito de Compra</h1>

    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Detalle</th>
                <th>Foto</th>
                <th>Precio</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td>{{ producto.item }}</td>
                    <td>{{ producto.detalle }}</td>
                    <td><img src="{{ producto.foto.url }}" width="100" height="100" alt="{{ producto.item }}"></td>
                    <td>{{ producto.precio }}</td>
                    <td>
                        <form action="{% url 'comprar_producto' producto.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Comprar</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}
</body>
</html>